http:
  addr: ":3000"

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  database: "my_project_db"
  ssl_mode: "disable"

logging:
  level: debug
plugins:
  tmdb:
    path: "plugins/wasm/tmdb/tmdb.wasm"
    allowedhosts: ["api.themoviedb.org"]
  tv:
    path: "plugins/wasm/tv/tv.wasm"
  movie:
    path: "plugins/wasm/movie/movie.wasm"
