// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type UsersRole struct {
	Name  string
	Rules []byte
}

type UsersRoleBinding struct {
	Name     string
	Role     string
	Subjects []byte
}

type UsersToken struct {
	ID       string
	UserName string
	Hash     []byte
	Created  time.Time
	Expires  *time.Time
}

type UsersUser struct {
	Name   string
	Groups []string
}
