// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"time"
)

const allBindings = `-- name: AllBindings :many
SELECT name, role, subjects FROM users.role_bindings ORDER BY name
`

func (q *Queries) AllBindings(ctx context.Context) ([]UsersRoleBinding, error) {
	rows, err := q.db.Query(ctx, allBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersRoleBinding
	for rows.Next() {
		var i UsersRoleBinding
		if err := rows.Scan(&i.Name, &i.Role, &i.Subjects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allRoles = `-- name: AllRoles :many
SELECT name, rules FROM users.roles ORDER BY name
`

func (q *Queries) AllRoles(ctx context.Context) ([]UsersRole, error) {
	rows, err := q.db.Query(ctx, allRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersRole
	for rows.Next() {
		var i UsersRole
		if err := rows.Scan(&i.Name, &i.Rules); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allTokens = `-- name: AllTokens :many
SELECT id, user_name, created, expires FROM users.tokens ORDER BY user_name, created
`

type AllTokensRow struct {
	ID       string
	UserName string
	Created  time.Time
	Expires  *time.Time
}

func (q *Queries) AllTokens(ctx context.Context) ([]AllTokensRow, error) {
	rows, err := q.db.Query(ctx, allTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllTokensRow
	for rows.Next() {
		var i AllTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Created,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allUsers = `-- name: AllUsers :many
SELECT name, groups FROM users.users ORDER BY name
`

func (q *Queries) AllUsers(ctx context.Context) ([]UsersUser, error) {
	rows, err := q.db.Query(ctx, allUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersUser
	for rows.Next() {
		var i UsersUser
		if err := rows.Scan(&i.Name, &i.Groups); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBinding = `-- name: DeleteBinding :execrows
DELETE FROM users.role_bindings WHERE name = $1
`

func (q *Queries) DeleteBinding(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBinding, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM users.roles WHERE name = $1
`

func (q *Queries) DeleteRole(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteToken = `-- name: DeleteToken :execrows
DELETE FROM users.tokens WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users.users WHERE name = $1
`

func (q *Queries) DeleteUser(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putBinding = `-- name: PutBinding :exec
INSERT INTO users.role_bindings (name, role, subjects) VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET role = EXCLUDED.role, subjects = EXCLUDED.subjects
`

type PutBindingParams struct {
	Name     string
	Role     string
	Subjects []byte
}

func (q *Queries) PutBinding(ctx context.Context, arg PutBindingParams) error {
	_, err := q.db.Exec(ctx, putBinding, arg.Name, arg.Role, arg.Subjects)
	return err
}

const putRole = `-- name: PutRole :exec
INSERT INTO users.roles (name, rules) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET rules = EXCLUDED.rules
`

type PutRoleParams struct {
	Name  string
	Rules []byte
}

func (q *Queries) PutRole(ctx context.Context, arg PutRoleParams) error {
	_, err := q.db.Exec(ctx, putRole, arg.Name, arg.Rules)
	return err
}

const putToken = `-- name: PutToken :execrows
INSERT INTO users.tokens (id, user_name, hash, created, expires)
SELECT $1::text, name, $2::bytea, $3::timestamptz, $4::timestamptz
FROM users.users WHERE name = $5
`

type PutTokenParams struct {
	ID       string
	Hash     []byte
	Created  time.Time
	Expires  *time.Time
	UserName string
}

func (q *Queries) PutToken(ctx context.Context, arg PutTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, putToken,
		arg.ID,
		arg.Hash,
		arg.Created,
		arg.Expires,
		arg.UserName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putUser = `-- name: PutUser :exec
INSERT INTO users.users (name, groups) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET groups = EXCLUDED.groups
`

type PutUserParams struct {
	Name   string
	Groups []string
}

func (q *Queries) PutUser(ctx context.Context, arg PutUserParams) error {
	_, err := q.db.Exec(ctx, putUser, arg.Name, arg.Groups)
	return err
}

const tokenByHash = `-- name: TokenByHash :one
SELECT t.id, t.user_name, t.created, t.expires, u.groups
FROM users.tokens t JOIN users.users u ON u.name = t.user_name WHERE t.hash = $1
`

type TokenByHashRow struct {
	ID       string
	UserName string
	Created  time.Time
	Expires  *time.Time
	Groups   []string
}

func (q *Queries) TokenByHash(ctx context.Context, hash []byte) (TokenByHashRow, error) {
	row := q.db.QueryRow(ctx, tokenByHash, hash)
	var i TokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Created,
		&i.Expires,
		&i.Groups,
	)
	return i, err
}
